version: "3.8"

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    env_file:
      - core/env/env.local
    depends_on:
      - pgdb
      - redis
  celery:
    restart: always
    build: .
    container_name: celery
    entrypoint: /bin/sh
    command: ./docker.celery.sh
    # command: celery -A core worker -B -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - core/env/env.local
    depends_on:
      - django
      - redis
      # - rabbitmq
  # flower:
  #   image: mher/flower
  #   command: ["--app core", "--url_prefix=flower", "--broker=redis://redis"]
  #   ports:
  #     - 5555:5555
  #   restart: unless-stopped
  pgdb:
    image: postgres:alpine
    container_name: pgdb
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    restart: always
    image: redis:alpine
    container_name: redis
    volumes:
      - redisdata:/data
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]
  # rabbitmq:
  #     restart: always
  #     image: rabbitmq:latest

volumes:
  pgdata:
  redisdata:
