# Generated by Django 3.1.3 on 2020-11-28 04:57

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20201114_2329'),
        ('shop', '0004_auto_20201128_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('number', models.CharField(default='', max_length=100, unique=True, verbose_name='order number')),
                ('status', django_fsm.FSMField(choices=[('NW', 'New'), ('CF', 'Confirmed'), ('CX', 'Canceled'), ('SP', 'Shipped'), ('RT', 'Returned')], default='NW', max_length=50, protected=True, verbose_name='order status')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='subtotal')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default='500', max_digits=5, verbose_name='shipping fee')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.address', verbose_name='address')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='unit price')),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='order.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsku', verbose_name='sku')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('star', models.PositiveSmallIntegerField(choices=[(5, 'Very satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Unsatisfied'), (1, 'Very unsatisfied')], default=5, verbose_name='stars')),
                ('comment', models.TextField(verbose_name='comment')),
                ('order_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='order.orderproduct', verbose_name='order product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('number', models.CharField(default='', max_length=100, verbose_name='payment number')),
                ('status', django_fsm.FSMField(choices=[('PD', 'Pending'), ('SC', 'Succeeded'), ('EX', 'Expired'), ('RF', 'Refunded')], default='PD', max_length=50, protected=True, verbose_name='payment status')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='amount')),
                ('method', models.CharField(choices=[('CARD', 'Credit Card')], default='CARD', max_length=10, verbose_name='payment method')),
                ('session_id', models.CharField(default='', max_length=250, verbose_name='payment session id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.payment', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.user', verbose_name='user'),
        ),
    ]
