# Generated by Django 3.1.3 on 2020-12-14 15:15

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201203_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_at',
            field=models.DateTimeField(null=True, verbose_name='return at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('NW', 'New'), ('CF', 'Confirmed'), ('CL', 'Cancelling'), ('CX', 'Cancelled'), ('SP', 'Shipped'), ('RT', 'Returning'), ('CP', 'Completed')], default='NW', max_length=50, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_fsm.FSMField(choices=[('PD', 'Pending'), ('SC', 'Succeeded'), ('EX', 'Expired'), ('RF', 'Refunded')], default='PD', max_length=50, verbose_name='payment status'),
        ),
    ]
