# Generated by Django 3.1.4 on 2020-12-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201220_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'permissions': [('ship_order', 'can ship orders'), ('cancel_order', 'can cancel orders')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',), 'permissions': [('refund', 'can create a refund')]},
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
