# Generated by Django 3.1.3 on 2020-11-13 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('recipient', models.CharField(max_length=50, verbose_name='recipient')),
                ('phone_no', models.CharField(max_length=50, verbose_name='phone number')),
                ('addr', models.CharField(max_length=250, verbose_name='address')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('zip_code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+')], verbose_name='zip code')),
                ('is_default', models.BooleanField(default=False, verbose_name='default address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
