# Generated by Django 3.1.3 on 2020-11-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
