# Generated by Django 3.1.3 on 2020-11-17 16:58

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('desc', models.CharField(max_length=250, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/category/', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('desc', models.CharField(max_length=250, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('desc', models.CharField(max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU',
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('desc', models.CharField(max_length=250, verbose_name='brief')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50, verbose_name='unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='stock')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='sales')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='brand/maker')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='media/sku_cover/', verbose_name='cover image')),
                ('status', models.CharField(choices=[('ON', 'On the shelf'), ('OFF', 'Off the shelf')], default='ON', max_length=3, verbose_name='shelf status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='shop.category', verbose_name='category')),
                ('origin', models.ForeignKey(default='Japan', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sku', to='shop.origin', verbose_name='place of origin')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='shop.productspu', verbose_name='SPU')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='media/sku_image/', verbose_name='image')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsku', verbose_name='SKU')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('index', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='index no.')),
                ('image', models.ImageField(upload_to='media/banner/', verbose_name='image')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsku', verbose_name='SKU')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['name'], name='shop_produc_name_f2c6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['desc', 'detail'], name='shop_produc_desc_4f8017_idx'),
        ),
    ]
