# Generated by Django 3.1.3 on 2020-11-19 15:46

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productsku',
            name='shop_produc_desc_4f8017_idx',
        ),
        migrations.RenameField(
            model_name='productsku',
            old_name='desc',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='productsku',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='images', to='shop.productsku', verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(
                fields=['summary', 'detail'], name='shop_produc_summary_f72e1d_idx'),
        ),
        TrigramExtension(),
    ]
