# Generated by Django 3.1.3 on 2020-12-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201128_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsku',
            options={'get_latest_by': ('created_at',), 'verbose_name': 'SKU', 'verbose_name_plural': 'SKU'},
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='shop.productsku', verbose_name='SKU'),
        ),
    ]
